public with sharing class ServiceAppointmentConstants {
    public static final String FIELD_API_NAME_OWNER = 'OwnerId';
    public static final String FIELD_API_NAME_RESCHEDULE_COUNT = 'Reschedule_Count__c';
    public static final String FIELD_API_NAME_STATUS = 'Status';
    public static final String FIELD_API_NAME_SCHEDULED_START = 'SchedStartTime';
    public static final String STATUS_COMPLETED = 'Completed';
    public static final String STATUS_CANCELLED = 'Cancelled';
    public static final String STATUS_NO_SHOW = 'No Show';
    public static final String STATUS_SCHEDULED = 'Scheduled';
    public static final String TEMPLATE_TOUR_BOOKED_NOTIFICATION = 'OrgC_Tour_Booked_Notification_Template';
    public static final String TEMPLATE_TOUR_COMPLETED_NOTIFICATION = 'OC_Tour_Completed_Notification_Template';
    public static final String TEMPLATE_TOUR_REASSIGNED_NOTIFICATION = 'OrgC_Tour_Reassigned_Template';
    public static final String TEMPLATE_TOUR_RESCHEDULED_NOTIFICATION = 'OrgC_Tour_Reschedule_Template';
    public static final String TOUR_FORMAT_IN_PERSON = 'In-Person';
}